import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import {
  Layout,
  MessageSquare,
  Copy,
  Check,
  MousePointer2,
  Smartphone,
  Monitor,
  Download,
  ExternalLink,
  Share2,
  Zap,
  Shield,
  Flame,
  Trophy,
  Cat,
  Star,
  Quote
} from 'lucide-react';
import type { CopyResponse } from '../services/ai';
import { cn } from '../lib/utils';

interface CopyGeneratorProps {
  data: CopyResponse;
  ideaName?: string;
}

export const CopyGenerator: React.FC<CopyGeneratorProps> = ({ data, ideaName }) => {
  const brandName = ideaName?.split(' ').slice(0, 2).join('') || 'STARTUP';
  const [copied, setCopied] = useState<string | null>(null);
  const [isRewriting, setIsRewriting] = useState(false);
  const [showCatApproval, setShowCatApproval] = useState(false);
  const [isSyncing, setIsSyncing] = useState(false);
  const [syncStatus, setSyncStatus] = useState<'idle' | 'syncing' | 'success'>('idle');

  // Re-trigger animations when data changes
  useEffect(() => {
    setIsRewriting(true);
    const timer = setTimeout(() => {
      setIsRewriting(false);
      setShowCatApproval(true);
      setTimeout(() => setShowCatApproval(false), 3000);
    }, 1500);
    return () => clearTimeout(timer);
  }, [data]);

  const handleCopy = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopied(id);
    setTimeout(() => setCopied(null), 2000);
  };

  const exportToHtml = () => {
    const htmlContent = generatePreviewHtml();
    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${data.hero_headline.toLowerCase().replace(/\s+/g, '-')}-mvp.html`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const exportToDoc = () => {
    const docContent = `
      STARTUP COPILOT - STRATEGY EXPORT
      =================================
      
      HERO HEADLINE:
      ${data.hero_headline}
      
      SUBHEADLINE:
      ${data.subheadline}
      
      VALUE PROPOSITIONS:
      ${data.value_props.map((p, i) => `${i + 1}. ${p}`).join('\n')}
      
      CTA:
      ${data.cta}
      
      ELEVATOR PITCH SCRIPT:
      ${data.pitch_script}
      
      ---------------------------------
      Generated by Startup Copilot AI
    `;

    const blob = new Blob([docContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'copy-strategy.doc';
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleNotionSync = () => {
    setIsSyncing(true);
    setSyncStatus('syncing');

    // Simulate high-tech sync
    setTimeout(() => {
      setSyncStatus('success');
      setTimeout(() => {
        setIsSyncing(false);
        setSyncStatus('idle');
        // Open a fake success page or Notion-style view
        alert("🚀 Connected to Notion! Page created in 'Startup Workspace'.");
      }, 2000);
    }, 3000);
  };

  const shareToWhatsApp = () => {
    const message = `🚀 Check out my startup elevator pitch generated by Startup Copilot AI:\n\n"${data.pitch_script}"\n\nBuild your own at: start-up-copilot.vercel.app`;
    const encodedMessage = encodeURIComponent(message);
    window.open(`https://wa.me/?text=${encodedMessage}`, '_blank');
  };

  const generatePreviewHtml = () => {
    return `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${data.hero_headline} | MVP Launch</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    <style>
        body { 
          font-family: 'Plus Jakarta Sans', sans-serif; 
          scroll-behavior: smooth;
        }
        .gradient-bg {
          background: radial-gradient(circle at top right, #ecfdf5 0%, #ffffff 100%);
        }
        .glass {
          background: rgba(255, 255, 255, 0.85);
          backdrop-filter: blur(16px);
          border: 1px solid rgba(255, 255, 255, 0.4);
        }
        .animate-in {
          animation: fadeUp 1.2s cubic-bezier(0.16, 1, 0.3, 1) forwards;
          opacity: 0;
        }
        @keyframes fadeUp {
          from { opacity: 0; transform: translateY(40px); }
          to { opacity: 1; transform: translateY(0); }
        }
        .nav-link:hover::after {
          width: 100%;
        }
        .nav-link::after {
          content: '';
          position: absolute;
          bottom: -2px;
          left: 0;
          width: 0;
          height: 2px;
          background: #10b981;
          transition: width 0.3s ease;
        }
    </style>
</head>
<body class="bg-white text-slate-900 selection:bg-emerald-100 selection:text-emerald-900">
    <nav class="sticky top-0 z-50 glass px-6 py-4 flex justify-between items-center max-w-7xl mx-auto rounded-b-[2rem] shadow-sm border-x border-b">
        <div class="flex items-center gap-2 group cursor-pointer">
            <div class="w-10 h-10 bg-slate-900 rounded-2xl shadow-lg flex items-center justify-center transform group-hover:bg-emerald-500 transition-all duration-500">
              <svg class="text-white w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"></path></svg>
            </div>
            <span class="font-black text-xl tracking-tighter uppercase">${brandName.slice(0, -3)}<span class="text-emerald-500">${brandName.slice(-3)}</span></span>
        </div>
        <div class="hidden md:flex items-center gap-8">
          <a href="#features" class="relative nav-link text-[10px] font-black uppercase tracking-widest text-slate-600">Solutions</a>
          <a href="#about" class="relative nav-link text-[10px] font-black uppercase tracking-widest text-slate-600">Company</a>
          <button onclick="handleCTA()" class="bg-emerald-600 text-white px-7 py-3 rounded-2xl font-black text-[10px] uppercase tracking-widest shadow-xl shadow-emerald-200 hover:bg-slate-900 transition-all active:scale-95">
              Launch Now
          </button>
        </div>
    </nav>

    <main>
        <!-- Hero Section -->
        <section class="gradient-bg border-b border-slate-50 relative overflow-hidden">
          <div class="absolute inset-0 opacity-20 pointer-events-none" style="background-image: radial-gradient(#10b981 0.5px, transparent 0.5px); background-size: 24px 24px;"></div>
          <div class="max-w-6xl mx-auto px-6 py-32 text-center text-balance relative">
              <div class="inline-flex items-center gap-2 px-4 py-1.5 bg-emerald-50 border border-emerald-100 rounded-full mb-10 animate-in">
                  <span class="w-2 h-2 bg-emerald-500 rounded-full animate-pulse"></span>
                  <span class="text-[9px] font-black text-emerald-700 uppercase tracking-[0.3em]">Live Platform Generation</span>
              </div>
              <h1 class="text-5xl md:text-8xl font-black text-slate-900 mb-8 leading-[0.95] tracking-tighter animate-in" style="animation-delay: 0.1s">
                  ${data.hero_headline}
              </h1>
              <p class="text-xl md:text-2xl text-slate-500 mb-14 max-w-3xl mx-auto leading-relaxed animate-in font-medium opacity-80" style="animation-delay: 0.2s">
                  ${data.subheadline}
              </p>
              <div class="flex flex-col sm:flex-row gap-5 justify-center animate-in" style="animation-delay: 0.3s">
                  <button onclick="handleCTA()" class="bg-emerald-600 text-white px-12 py-6 rounded-[2rem] font-black text-lg shadow-2xl shadow-emerald-100 hover:bg-slate-900 transition-all active:scale-95 flex items-center justify-center gap-3">
                      Start Your Journey
                      <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8l4 4m0 0l-4 4m4-4H3"></path></svg>
                  </button>
                  <a href="#features" class="bg-white text-slate-900 px-12 py-6 rounded-[2rem] font-black text-lg border-2 border-slate-100 hover:border-emerald-200 transition-all flex items-center justify-center">
                      Explore Vision
                  </a>
              </div>
          </div>
        </section>

        <!-- Features Grid -->
        <section id="features" class="max-w-7xl mx-auto px-6 py-40">
            <div class="flex flex-col md:flex-row md:items-end justify-between gap-8 mb-24 animate-in">
              <div class="max-w-xl">
                <h2 class="text-4xl md:text-6xl font-black mb-6 tracking-tighter text-slate-900">Core Foundations.</h2>
                <p class="text-slate-500 text-lg font-medium opacity-80">We don't just build cards; we architect sustainable growth strategies for future-focused founders.</p>
              </div>
              <div class="hidden md:block h-[1px] flex-1 bg-slate-100 mb-6"></div>
            </div>
            <div class="grid md:grid-cols-3 gap-12">
                ${data.value_props.map((prop, i) => `
                    <div class="bg-slate-50 p-12 rounded-[4rem] border border-transparent hover:bg-white hover:border-emerald-100 hover:shadow-[0_40px_80px_-20px_rgba(16,185,129,0.15)] transition-all duration-700 group animate-in" style="animation-delay: ${0.4 + (i * 0.1)}s">
                        <div class="w-16 h-16 bg-white rounded-3xl flex items-center justify-center mb-10 shadow-sm border border-slate-100 group-hover:scale-110 group-hover:bg-emerald-500 group-hover:text-white transition-all duration-500">
                            <svg class="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z"></path></svg>
                        </div>
                        <h3 class="font-black text-2xl text-slate-900 mb-4 tracking-tight">Strategy ${i + 1}</h3>
                        <p class="text-slate-500 leading-relaxed font-medium text-lg italic opacity-85">"${prop}"</p>
                    </div>
                `).join('')}
            </div>
        </section>

        <!-- Testimonial Section -->
        <section id="about" class="py-32 bg-slate-900 rounded-[5rem] mx-6 mb-32 overflow-hidden relative shadow-2xl">
            <div class="absolute top-0 right-0 w-[500px] h-[500px] bg-emerald-500 rounded-full blur-[150px] opacity-20 -mr-64 -mt-64 text-emerald-500 animate-pulse"></div>
            <div class="absolute bottom-0 left-0 w-[500px] h-[500px] bg-slate-800 rounded-full blur-[150px] opacity-10 -ml-64 -mb-64"></div>
            
            <div class="max-w-4xl mx-auto px-6 text-center relative z-10">
                <div class="w-20 h-20 bg-emerald-500/10 rounded-full flex items-center justify-center mx-auto mb-10 border border-emerald-500/20">
                  <svg class="text-emerald-400 w-10 h-10" fill="currentColor" viewBox="0 0 20 20"><path d="M10.394 2.813a1 1 0 00-.458-.022l-7.141 1.428a1 1 0 00-.793.793L.575 12.154a1 1 0 00.707 1.183l7.141 1.428a1 1 0 001.183-.707l1.428-7.141a1 1 0 00-.707-1.183l-7.141-1.428z"></path></svg>
                </div>
                <p class="text-emerald-400 text-[10px] font-black uppercase tracking-[0.5em] mb-10">Global Recognition</p>
                <p class="text-3xl md:text-5xl font-black text-white mb-12 italic leading-[1.15] tracking-tight">
                    "This architecture enabled us to scale from concept to customers in record time. The precision of the value props is unmatched."
                </p>
                <div class="flex flex-col items-center gap-5">
                    <div class="w-20 h-20 bg-gradient-to-tr from-emerald-500 to-teal-500 rounded-full border-4 border-slate-800 shadow-xl overflow-hidden flex items-center justify-center">
                       <span class="text-white font-black text-2xl">SJ</span>
                    </div>
                    <div class="text-center">
                        <p class="text-white font-black text-xl tracking-tight">Sarah Jenkins</p>
                        <p class="text-emerald-500/60 text-[9px] font-black uppercase tracking-[0.2em]">CTO, TechSprint Global</p>
                    </div>
                </div>
            </div>
        </section>

        <!-- Final CTA -->
        <section class="max-w-5xl mx-auto px-6 py-40 text-center animate-in" style="animation-delay: 0.5s">
            <h2 class="text-5xl md:text-7xl font-black mb-12 tracking-tighter">Own the market.</h2>
            <button onclick="handleCTA()" class="bg-emerald-600 text-white px-14 py-7 rounded-[2.5rem] font-black text-xl shadow-[0_20px_40px_rgba(16,185,129,0.3)] hover:bg-slate-900 transition-all hover:scale-105 active:scale-95">
                Launch My Vision
            </button>
            <p class="mt-10 text-slate-400 font-bold text-xs uppercase tracking-[0.2em]">Limited early access slots available.</p>
        </section>
    </main>

    <footer class="py-24 text-center border-t border-slate-50 bg-white">
        <div class="flex justify-center gap-16 mb-12 font-black text-[9px] uppercase tracking-[0.3em] text-slate-400">
            <span class="cursor-pointer hover:text-emerald-600 transition-colors">Documentation</span>
            <span class="cursor-pointer hover:text-emerald-600 transition-colors">Security</span>
            <span class="cursor-pointer hover:text-emerald-600 transition-colors">API</span>
        </div>
        <p class="text-[10px] font-black text-slate-200 uppercase tracking-[1em] mb-6">${brandName} CORE</p>
        <div class="flex items-center justify-center gap-3">
          <div class="w-2 h-2 bg-emerald-500 rounded-full animate-pulse shadow-[0_0_10px_rgba(16,185,129,0.5)]"></div>
          <span class="text-[8px] font-black text-slate-400 uppercase tracking-widest italic">Encrypted Connection Active</span>
        </div>
    </footer>

    <!-- INTERACTIVE SCRIPTS -->
    <script>
      function handleCTA() {
        const email = prompt("To deploy your version of ${data.hero_headline}, enter your secure email:");
        if (email) {
          alert("� Authentication Successful! Building your deployment environment for " + email + " now...");
        }
      }

      const observer = new IntersectionObserver((entries) => {
        entries.forEach(entry => {
          if (entry.isIntersecting) {
            entry.target.style.opacity = "1";
            entry.target.classList.add('animate-in');
          }
        });
      }, { threshold: 0.1 });

      document.querySelectorAll('.animate-in').forEach(el => observer.observe(el));
    </script>
</body>
</html>`;
  };

  // Mock score calculation
  const score = Math.floor(80 + Math.random() * 15);
  const metrics = [
    { label: 'Clarity', val: 92 },
    { label: 'Emotion', val: 88 },
    { label: 'Conversion', val: 84 },
  ];

  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-12">
      {/* Copy Sections */}
      <div className="space-y-8">
        <div className="flex items-center justify-between">
          <h2 className="text-2xl font-black text-slate-900 flex items-center gap-2 tracking-tighter uppercase italic">
            <Layout className="text-indigo-600" />
            MVP Website Architecture
          </h2>
        </div>

        {/* AI Score Widget */}
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-indigo-600 rounded-3xl p-6 text-white shadow-xl shadow-indigo-200 relative overflow-hidden"
        >
          <div className="relative z-10">
            <div className="flex justify-between items-start mb-4">
              <div>
                <span className="text-indigo-200 text-[10px] uppercase font-bold tracking-widest">AI Copy Score</span>
                <div className="text-4xl font-black">{score}%</div>
              </div>
              <div className="p-3 bg-white/10 rounded-2xl backdrop-blur-md">
                <Trophy className="text-yellow-400" />
              </div>
            </div>
            <div className="grid grid-cols-3 gap-4 border-t border-white/10 pt-4">
              {metrics.map((m) => (
                <div key={m.label}>
                  <div className="text-[10px] text-indigo-200 font-medium mb-1">{m.label}</div>
                  <div className="h-1.5 bg-white/10 rounded-full overflow-hidden">
                    <motion.div
                      initial={{ width: 0 }}
                      animate={{ width: `${m.val}%` }}
                      transition={{ duration: 1, delay: 0.5 }}
                      className="h-full bg-white"
                    />
                  </div>
                </div>
              ))}
            </div>
          </div>
          <div className="absolute top-0 right-0 w-32 h-32 bg-white/5 rounded-full -mr-16 -mt-16 blur-3xl" />
        </motion.div>

        <div className="space-y-6">
          <CopyBlock
            label="Hero Headline"
            content={data.hero_headline}
            onCopy={() => handleCopy(data.hero_headline, 'headline')}
            isCopied={copied === 'headline'}
          />
          <CopyBlock
            label="Subheadline"
            content={data.subheadline}
            onCopy={() => handleCopy(data.subheadline, 'sub')}
            isCopied={copied === 'sub'}
          />

          {/* Enhanced Value Props */}
          <div className="bg-white p-6 rounded-3xl shadow-sm border border-slate-100 group">
            <div className="flex items-center justify-between mb-4">
              <span className="text-[10px] uppercase font-bold text-indigo-500">Value Propositions</span>
              <div className="flex gap-2">
                <span className="flex items-center gap-1 text-[9px] font-bold px-2 py-0.5 bg-orange-50 text-orange-600 rounded-full">
                  <Flame size={8} /> High Impact
                </span>
                <span className="flex items-center gap-1 text-[9px] font-bold px-2 py-0.5 bg-blue-50 text-blue-600 rounded-full">
                  <Zap size={8} /> Fast Dev
                </span>
              </div>
            </div>
            <ul className="space-y-4">
              {data.value_props.map((prop, idx) => (
                <motion.li
                  key={idx}
                  initial={{ opacity: 0, x: -10 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: idx * 0.1 }}
                  className="flex items-start gap-3 group/item hover:bg-slate-50 p-3 -m-3 rounded-2xl transition-all border border-transparent hover:border-slate-100"
                >
                  <motion.div
                    initial={{ scale: 0 }}
                    animate={{ scale: 1 }}
                    transition={{ type: "spring", stiffness: 300, damping: 20, delay: idx * 0.1 + 0.2 }}
                    className="mt-1 p-1 bg-indigo-50 rounded-lg group-hover/item:bg-indigo-100 transition-colors"
                  >
                    <Check size={12} className="text-indigo-600" />
                  </motion.div>
                  <p className="text-sm text-slate-700 font-medium leading-relaxed">{prop}</p>
                </motion.li>
              ))}
            </ul>
          </div>

          {/* Elevator Pitch Upgrade */}
          <div className="bg-gradient-to-br from-slate-900 to-slate-800 p-8 rounded-[2rem] shadow-xl relative overflow-hidden group border-l-4 border-indigo-500">
            <div className="absolute top-4 right-6">
              <span className="text-[10px] font-black text-white px-3 py-1 bg-indigo-500 rounded-full uppercase tracking-tighter">Investor Ready</span>
            </div>
            <Quote className="text-slate-700 absolute -left-2 -top-2" size={80} />

            <div className="relative z-10">
              <span className="text-indigo-400 text-[10px] uppercase font-bold mb-4 block">Elevator Pitch Script</span>
              <div className="flex gap-4">
                <div className="flex-1">
                  <p className="text-white text-lg font-medium leading-relaxed italic mb-6">
                    "{data.pitch_script}"
                  </p>
                  <div className="flex gap-3">
                    <button
                      onClick={() => handleCopy(data.pitch_script, 'pitch')}
                      className="flex items-center gap-2 px-4 py-2 bg-white/10 hover:bg-white/20 text-white rounded-xl text-xs font-bold transition-all border border-white/5"
                    >
                      {copied === 'pitch' ? <Check size={14} className="text-emerald-400" /> : <Copy size={14} />}
                      Copy Script
                    </button>
                    <button
                      onClick={shareToWhatsApp}
                      className="flex items-center gap-2 px-4 py-2 bg-indigo-500/20 hover:bg-indigo-500/30 text-indigo-300 rounded-xl text-xs font-bold transition-all border border-indigo-500/30"
                    >
                      <Share2 size={14} />
                      Share
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Real Tool Buttons Mockup */}
        <div className="pt-4 border-t border-slate-100">
          <div className="flex flex-wrap gap-3">
            <button
              onClick={exportToHtml}
              className="flex items-center gap-2 px-4 py-3 bg-white border border-slate-200 text-slate-600 rounded-2xl text-[10px] font-black uppercase hover:bg-slate-50 hover:border-indigo-200 transition-all shadow-sm active:scale-95"
            >
              <Download size={14} /> landing.html
            </button>
            <button
              onClick={handleNotionSync}
              disabled={isSyncing}
              className={cn(
                "flex items-center gap-2 px-4 py-3 border rounded-2xl text-[10px] font-black uppercase transition-all shadow-sm active:scale-95 relative overflow-hidden",
                syncStatus === 'success' ? "bg-emerald-50 border-emerald-200 text-emerald-600" :
                  isSyncing ? "bg-slate-50 border-slate-100 text-slate-400 cursor-wait" :
                    "bg-white border-slate-200 text-slate-600 hover:bg-slate-50 hover:border-indigo-200"
              )}
            >
              <AnimatePresence mode="wait">
                {isSyncing ? (
                  <motion.div
                    key="syncing"
                    initial={{ opacity: 0, scale: 0.8 }}
                    animate={{ opacity: 1, scale: 1 }}
                    exit={{ opacity: 0, scale: 1.2 }}
                    className="flex items-center gap-2"
                  >
                    <motion.div
                      animate={{ rotate: 360 }}
                      transition={{ duration: 1, repeat: Infinity, ease: "linear" }}
                    >
                      <ExternalLink size={14} />
                    </motion.div>
                    Syncing...
                  </motion.div>
                ) : syncStatus === 'success' ? (
                  <motion.div
                    key="success"
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="flex items-center gap-2"
                  >
                    <Check size={14} /> Synced!
                  </motion.div>
                ) : (
                  <motion.div
                    key="idle"
                    className="flex items-center gap-2"
                  >
                    <ExternalLink size={14} /> Sync to Notion
                  </motion.div>
                )}
              </AnimatePresence>
            </button>
            <button
              onClick={exportToDoc}
              className="flex items-center gap-2 px-4 py-3 bg-white border border-slate-200 text-slate-600 rounded-2xl text-[10px] font-black uppercase hover:bg-slate-50 hover:border-indigo-200 transition-all shadow-sm active:scale-95"
            >
              <Check size={14} /> Copy as .doc
            </button>
          </div>
        </div>
      </div>

      {/* Preview Mockup */}
      <div className="space-y-6 flex flex-col items-center">
        <h3 className="text-sm font-bold text-slate-400 uppercase tracking-widest flex items-center gap-2 w-full">
          <Layout size={16} />
          Visual Preview
        </h3>

        <div className="relative w-full flex justify-center py-12 bg-slate-50 rounded-[3rem] border-2 border-dashed border-slate-200 min-h-[700px]">
          {/* Background Gradient Blob */}
          <div className="absolute inset-0 overflow-hidden pointer-events-none">
            <div className="absolute -top-[10%] -left-[10%] w-[40%] h-[40%] bg-indigo-100 rounded-full blur-[100px] opacity-50" />
            <div className="absolute -bottom-[10%] -right-[10%] w-[40%] h-[40%] bg-blue-100 rounded-full blur-[100px] opacity-50" />
          </div>

          <AnimatePresence mode="wait">
            {isRewriting && (
              <motion.div
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0 }}
                className="absolute top-24 z-50 flex items-center gap-3 bg-white/90 backdrop-blur-sm px-6 py-3 rounded-2xl shadow-xl border border-indigo-100"
              >
                <div className="w-2 h-2 bg-indigo-600 rounded-full animate-pulse" />
                <span className="text-xs font-black text-indigo-600 uppercase tracking-widest">AI is Rewriting...</span>
                <div className="flex gap-1">
                  {[0, 1, 2].map((i) => (
                    <motion.div
                      key={i}
                      animate={{ opacity: [0.3, 1, 0.3] }}
                      transition={{ duration: 1, repeat: Infinity, delay: i * 0.2 }}
                      className="w-1 h-1 bg-indigo-300 rounded-full"
                    />
                  ))}
                </div>
              </motion.div>
            )}
          </AnimatePresence>

          <motion.div
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            whileHover={{
              rotateX: 2,
              rotateY: 5,
              scale: 1.01,
              transition: { duration: 0.3 }
            }}
            className="sticky top-8 bg-slate-900 shadow-[0_50px_100px_-20px_rgba(0,0,0,0.3)] transition-all duration-700 ease-in-out border-8 border-slate-800 overflow-hidden rounded-[3rem] p-4 aspect-[9/19] w-[320px]"
          >
            <div className="bg-white h-full w-full rounded-[1.5rem] overflow-hidden relative flex flex-col">
              {/* Browser Header */}
              <div className="h-6 bg-slate-50 flex items-center px-4 gap-1 border-b border-slate-100 flex-shrink-0">
                <div className="w-1.5 h-1.5 rounded-full bg-rose-400" />
                <div className="w-1.5 h-1.5 rounded-full bg-amber-400" />
                <div className="w-1.5 h-1.5 rounded-full bg-emerald-400" />
                <div className="ml-2 flex-1 flex items-center justify-center relative">
                  <div className="bg-slate-200/50 h-3 w-full max-w-[200px] rounded-full flex items-center px-2">
                    <div className="w-1 h-1 bg-slate-400 rounded-full mr-1.5" />
                    <div className="bg-slate-300 h-1 w-24 rounded-full" />
                  </div>
                  <div className="absolute right-0 flex items-center gap-1.5">
                    <div className="w-1.5 h-1.5 bg-emerald-500 rounded-full animate-pulse" />
                    <span className="text-[7px] font-black text-emerald-600 uppercase tracking-tighter">Live</span>
                  </div>
                </div>
              </div>

              {/* LIVE HTML PREVIEW (Iframe) */}
              <div className={cn(
                "flex-1 transition-all duration-500 overflow-hidden",
                isRewriting ? "blur-md opacity-50 grayscale" : "blur-0 opacity-100 grayscale-0"
              )}>
                <iframe
                  title="MVP Preview"
                  className="w-full h-full border-none"
                  srcDoc={generatePreviewHtml()}
                />
              </div>

              {/* Cat Approved Stamp */}
              <AnimatePresence>
                {showCatApproval && (
                  <motion.div
                    initial={{ scale: 2, opacity: 0, rotate: 20 }}
                    animate={{ scale: 1, opacity: 1, rotate: -15 }}
                    exit={{ opacity: 0, scale: 0.5 }}
                    className="absolute bottom-10 right-10 z-50 pointer-events-none"
                  >
                    <div className="relative">
                      <div className="bg-emerald-500 text-white p-3 rounded-full shadow-2xl flex items-center gap-2 border-4 border-white">
                        <Cat size={24} />
                        <span className="font-black text-xs uppercase italic tracking-tighter">Approved!</span>
                      </div>
                      <motion.div
                        initial={{ opacity: 0, scale: 3 }}
                        animate={{ opacity: 0.4, scale: 1 }}
                        className="absolute inset-0 bg-emerald-500 rounded-full blur-xl -z-10"
                      />
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>

            {/* Micro Cat Delight (Paw) */}
            <motion.div
              className="absolute -bottom-8 -right-8 text-indigo-900 p-2 opacity-20 pointer-events-none"
              animate={{ y: [0, -10, 0], rotate: [0, 5, 0] }}
              transition={{ duration: 4, repeat: Infinity }}
            >
              <Cat size={64} />
            </motion.div>
          </motion.div>
        </div>
      </div>
    </div>
  );
};

const CopyBlock = ({ label, content, onCopy, isCopied }: { label: string, content: string, onCopy: () => void, isCopied: boolean }) => {
  return (
    <div className="bg-white p-6 rounded-3xl shadow-sm border border-slate-100 group relative hover:border-indigo-100 transition-all">
      <div className="flex justify-between items-center mb-2">
        <span className="text-[10px] uppercase font-bold text-indigo-500">{label}</span>
        <div className="flex items-center gap-1">
          <button
            onClick={onCopy}
            className="p-2 hover:bg-slate-50 rounded-xl transition-colors text-slate-400 hover:text-indigo-600"
          >
            {isCopied ? <Check size={16} className="text-emerald-500" /> : <Copy size={16} />}
          </button>
        </div>
      </div>
      <p className="text-slate-800 font-bold text-lg leading-tight uppercase tracking-tight">
        {content}
      </p>
    </div>
  );
};


