import React from 'react';
import { motion, AnimatePresence } from 'motion/react';
import {
  Calendar, Rocket, Milestone, Cpu, ShieldAlert,
  Copy, Check, FileText, Github, ExternalLink,
  AlertTriangle, Layout, Server, Database, Sparkles,
  ChevronDown, ChevronUp, ArrowRight
} from 'lucide-react';
import type { RoadmapResponse } from '../services/ai';
import { cn } from '../lib/utils';
import confetti from 'canvas-confetti';

interface RoadmapGeneratorProps {
  data: RoadmapResponse;
}

export const RoadmapGenerator: React.FC<RoadmapGeneratorProps> = ({ data }) => {
  const [isSyncing, setIsSyncing] = React.useState<string | null>(null);
  const [copied, setCopied] = React.useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(JSON.stringify(data, null, 2));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExportPDF = () => {
    window.print();
  };

  const handleGithubSync = () => {
    setIsSyncing('github');

    // Generate a README.md content from the roadmap data
    const content = `# 🚀 MVP Project Vision: ${data.strategic_summary?.substring(0, 50) || 'New Venture'}...

## 🎯 Strategic Overview
${data.strategic_summary || 'Your AI Co-Founder has architected this roadmap to prioritize lean validation and core performance.'}

## 🛠️ Suggested Tech Stack
${data.suggested_tech_stack.map(t => `- [ ] **${t}**`).join('\n')}

## 📍 Phase 1: Foundation (Week 1)
### Goals
${data.week_1.goals.map(g => `- [ ] ${g}`).join('\n')}
### Key Features
${data.week_1.features.map(f => `- ${f}`).join('\n')}

## 🚀 Phase 2: Core Product (Month 1)
### Goals
${data.month_1.goals.map(g => `- [ ] ${g}`).join('\n')}
### Key Features
${data.month_1.features.map(f => `- ${f}`).join('\n')}

## 📈 Phase 3: Scale (Quarter 1)
### Goals
${data.quarter_1.goals.map(g => `- [ ] ${g}`).join('\n')}
### Key Features
${data.quarter_1.features.map(f => `- ${f}`).join('\n')}

---
*Generated by Startup Copilot — Your AI Co-Founder*`;

    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'MVP_ROADMAP.md';

    setTimeout(() => {
      link.click();
      URL.revokeObjectURL(url);
      setIsSyncing(null);
      confetti({
        particleCount: 150,
        spread: 100,
        origin: { y: 0.8 },
        colors: ['#6366f1', '#a855f7', '#d946ef']
      });
    }, 1500);
  };

  const handleNotionSync = () => {
    setIsSyncing('notion');
    setTimeout(() => {
      setIsSyncing(null);
      confetti({
        particleCount: 100,
        spread: 50,
        origin: { y: 0.8 },
        colors: ['#000000', '#6366f1']
      });
      // In a real app, this would use Notion API to create a page
      window.open('https://www.notion.so/new', '_blank');
    }, 1200);
  };

  // Tech Stack Grouping
  const techCategories = {
    Frontend: ['React', 'Vue', 'Next.js', 'Tailwind', 'Vite', 'CSS', 'HTML', 'Flutter', 'React Native', 'Typescript', 'Javascript'],
    Backend: ['Node', 'Python', 'Django', 'FastAPI', 'Go', 'Java', 'PHP', 'Rails', 'Express', 'Auth0', 'Firebase'],
    Infra: ['AWS', 'Vercel', 'Docker', 'K8s', 'SQL', 'MongoDB', 'Redis', 'Postgres', 'Supabase', 'Cloudflare', 'Prisma']
  };

  const groupedTech = {
    Frontend: data.suggested_tech_stack.filter(t => techCategories.Frontend.some(cat => t.toLowerCase().includes(cat.toLowerCase()))),
    Backend: data.suggested_tech_stack.filter(t => techCategories.Backend.some(cat => t.toLowerCase().includes(cat.toLowerCase()))),
    Infra: data.suggested_tech_stack.filter(t => techCategories.Infra.some(cat => t.toLowerCase().includes(cat.toLowerCase()))),
  };

  const otherTech = data.suggested_tech_stack.filter(t =>
    !groupedTech.Frontend.includes(t) &&
    !groupedTech.Backend.includes(t) &&
    !groupedTech.Infra.includes(t)
  );

  return (
    <div className="space-y-16">
      {/* Strategic Summary Header */}
      <motion.div
        initial={{ opacity: 0, y: 30 }}
        animate={{ opacity: 1, y: 0 }}
        className="bg-gradient-to-br from-indigo-600 via-indigo-700 to-violet-800 rounded-[2.5rem] p-8 md:p-12 text-white shadow-2xl shadow-indigo-200/50 relative overflow-hidden"
      >
        <div className="absolute top-0 right-0 w-96 h-96 bg-white/10 rounded-full -translate-y-1/2 translate-x-1/2 blur-[100px]" />
        <div className="absolute bottom-0 left-0 w-64 h-64 bg-indigo-400/20 rounded-full translate-y-1/2 -translate-x-1/2 blur-[80px]" />

        <div className="relative z-10">
          <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-8 mb-10">
            <div>
              <motion.div
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.2 }}
                className="flex items-center gap-3 mb-3"
              >
                <div className="p-2.5 bg-white/20 rounded-xl backdrop-blur-md shadow-inner">
                  <Sparkles className="text-amber-300 animate-pulse" size={24} />
                </div>
                <span className="text-indigo-100 font-black tracking-[0.2em] uppercase text-[10px]">Strategic AI Architecture</span>
              </motion.div>
              <h2 className="text-4xl md:text-5xl font-black text-white leading-tight">
                MVP Alpha <span className="text-indigo-200">Roadmap</span>
              </h2>
            </div>
            <div className="flex flex-wrap gap-4">
              <button
                onClick={handleCopy}
                disabled={copied}
                className="flex items-center gap-2 px-5 py-2.5 bg-white/10 hover:bg-white/20 border border-white/20 rounded-2xl text-sm font-bold transition-all backdrop-blur-md active:scale-95 disabled:opacity-50"
              >
                {copied ? <Check size={18} className="text-emerald-400" /> : <Copy size={18} />}
                {copied ? 'Copied' : 'JSON Feed'}
              </button>
              <button
                onClick={handleExportPDF}
                className="group flex items-center gap-2 px-6 py-2.5 bg-white text-indigo-700 hover:bg-indigo-50 rounded-2xl text-sm font-black transition-all shadow-xl shadow-indigo-950/20 active:scale-95"
              >
                <FileText size={18} className="group-hover:rotate-6 transition-transform" />
                Export Investor PDF
              </button>
            </div>
          </div>

          {data.strategic_summary && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.4 }}
              className="max-w-4xl relative"
            >
              <div className="absolute -left-6 top-0 bottom-0 w-1 bg-gradient-to-b from-amber-400 to-transparent rounded-full opacity-50" />
              <p className="text-indigo-50 text-xl md:text-2xl leading-relaxed font-medium italic pl-4">
                "{data.strategic_summary}"
              </p>
            </motion.div>
          )}

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.6 }}
            className="mt-12 flex flex-wrap gap-6"
          >
            <div className="flex gap-4">
              <button
                onClick={handleGithubSync}
                disabled={isSyncing === 'github'}
                className="flex items-center gap-2 px-4 py-2 bg-indigo-500/30 hover:bg-indigo-500/50 border border-indigo-400/30 rounded-xl text-xs font-black transition-all backdrop-blur-sm group disabled:opacity-50"
              >
                {isSyncing === 'github' ? (
                  <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                ) : (
                  <Github size={16} className="text-indigo-200 group-hover:text-white transition-colors" />
                )}
                {isSyncing === 'github' ? 'Generating Repo...' : 'Generate Github Repo'}
                <ArrowRight size={14} className="opacity-0 group-hover:opacity-100 -translate-x-2 group-hover:translate-x-0 transition-all" />
              </button>
              <button
                onClick={handleNotionSync}
                disabled={isSyncing === 'notion'}
                className="flex items-center gap-2 px-4 py-2 bg-indigo-500/30 hover:bg-indigo-500/50 border border-indigo-400/30 rounded-xl text-xs font-black transition-all backdrop-blur-sm group disabled:opacity-50"
              >
                {isSyncing === 'notion' ? (
                  <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                ) : (
                  <Rocket size={16} className="text-indigo-200 group-hover:text-white transition-colors" />
                )}
                {isSyncing === 'notion' ? 'Syncing...' : 'Sync to Notion'}
                <ArrowRight size={14} className="opacity-0 group-hover:opacity-100 -translate-x-2 group-hover:translate-x-0 transition-all" />
              </button>
            </div>
          </motion.div>
        </div>
      </motion.div>

      <div className="relative pt-12 pb-20 px-4 md:px-0">
        {/* Animated Vertical Line */}
        <div className="absolute left-8 md:left-1/2 top-0 bottom-0 w-1 bg-slate-100 -translate-x-1/2 hidden md:block rounded-full overflow-hidden">
          <motion.div
            initial={{ height: 0 }}
            whileInView={{ height: '100%' }}
            viewport={{ once: true }}
            transition={{ duration: 2, ease: "easeInOut" }}
            className="w-full bg-gradient-to-b from-indigo-600 via-indigo-400 to-violet-500"
          />
        </div>

        <div className="space-y-32">
          <TimelineItem
            title="Foundation"
            phase="PHASE 01"
            label="Validate & Structure"
            data={data.week_1}
            icon={<Calendar className="text-indigo-600" />}
            side="left"
            progress={100}
            delay={0.2}
          />
          <TimelineItem
            title="Core Engine"
            phase="PHASE 02"
            label="Build MVP Core"
            data={data.month_1}
            icon={<Milestone className="text-indigo-600" />}
            side="right"
            progress={60}
            delay={0.4}
          />
          <TimelineItem
            title="Scale-Up"
            phase="PHASE 03"
            label="Optimize & Growth"
            data={data.quarter_1}
            icon={<Rocket className="text-indigo-600" />}
            side="left"
            progress={20}
            delay={0.6}
          />
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="bg-white/50 backdrop-blur-xl p-10 rounded-[2.5rem] shadow-sm border border-indigo-50/50">
          <div className="flex items-center justify-between mb-8">
            <div className="flex items-center gap-3">
              <div className="p-3 bg-indigo-600 rounded-2xl shadow-lg shadow-indigo-200">
                <Cpu className="text-white" size={24} />
              </div>
              <div>
                <h3 className="font-black text-slate-900 text-xl">Architectural Stack</h3>
                <p className="text-slate-500 text-sm font-medium">Industry-standard suggested stack</p>
              </div>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <TechGroup title="Frontend" icon={<Layout size={16} />} items={groupedTech.Frontend} color="indigo" />
            <TechGroup title="Backend" icon={<Server size={16} />} items={groupedTech.Backend} color="violet" />
            <TechGroup title="Infrastructure" icon={<Database size={16} />} items={groupedTech.Infra} color="blue" />
          </div>

          {otherTech.length > 0 && (
            <div className="mt-8 pt-8 border-t border-slate-100">
              <span className="text-[10px] font-black uppercase tracking-widest text-slate-400 mb-4 block">Auxiliary Tech</span>
              <div className="flex flex-wrap gap-2">
                {otherTech.map((tech, idx) => (
                  <span key={idx} className="px-3 py-1 bg-slate-100 text-slate-600 rounded-lg text-xs font-bold border border-slate-200">
                    {tech}
                  </span>
                ))}
              </div>
            </div>
          )}
        </div>

        <motion.div
          whileHover={{ y: -5 }}
          className="bg-white p-10 rounded-[2.5rem] shadow-xl shadow-rose-100/50 border-l-8 border-l-rose-500 border-y border-r border-rose-50 relative overflow-hidden group"
        >
          <div className="absolute top-0 right-0 p-4 opacity-5 group-hover:opacity-10 transition-opacity">
            <ShieldAlert size={120} />
          </div>

          <div className="flex items-center gap-3 mb-8">
            <div className="p-3 bg-rose-50 rounded-2xl relative">
              <ShieldAlert className="text-rose-600 relative z-10" size={24} />
              <div className="absolute inset-0 bg-rose-400 rounded-2xl animate-ping opacity-20" />
            </div>
            <div>
              <h3 className="font-black text-slate-900 text-xl">Critical Risks</h3>
              <p className="text-rose-500 text-sm font-bold animate-pulse uppercase tracking-tighter text-[10px]">High Priority Watchlist</p>
            </div>
          </div>

          <ul className="space-y-4">
            {data.risks_to_watch.map((risk, idx) => (
              <motion.li
                initial={{ opacity: 0, x: 20 }}
                whileInView={{ opacity: 1, x: 0 }}
                transition={{ delay: idx * 0.1 }}
                key={idx}
                className="group/item flex gap-4 p-4 rounded-2xl bg-slate-50 border border-slate-100 hover:bg-rose-50/50 hover:border-rose-100 transition-all"
              >
                <div className="mt-1 p-1 bg-rose-100 rounded-lg group-hover/item:bg-rose-200 transition-colors">
                  <AlertTriangle size={14} className="text-rose-600" />
                </div>
                <span className="text-sm text-slate-700 font-semibold leading-relaxed">{risk}</span>
              </motion.li>
            ))}
          </ul>
        </motion.div>
      </div>
    </div>
  );
};

const TimelineItem = ({
  title, phase, label, data, icon, side, progress, delay
}: {
  title: string, phase: string, label: string, data: any, icon: React.ReactNode, side: 'left' | 'right', progress: number, delay: number
}) => {
  const [isExpanded, setIsExpanded] = React.useState(true);

  return (
    <div className={cn(
      "relative flex flex-col md:flex-row items-start md:items-center gap-8 md:gap-16",
      side === 'right' ? "md:flex-row-reverse" : ""
    )}>
      {/* Animated Node */}
      <div className="absolute left-8 md:left-1/2 -track-x-1/2 md:-translate-x-1/2 top-0 md:top-1/2 md:-translate-y-1/2 z-20">
        <motion.div
          initial={{ scale: 0 }}
          whileInView={{ scale: 1 }}
          viewport={{ once: true }}
          className="relative"
        >
          <div className="w-10 h-10 rounded-2xl bg-white border-[6px] border-indigo-100 flex items-center justify-center shadow-lg shadow-indigo-200/50">
            <motion.div
              animate={{ scale: [1, 1.2, 1] }}
              transition={{ repeat: Infinity, duration: 2 }}
              className="w-3 h-3 rounded-full bg-indigo-600 shadow-[0_0_15px_rgba(79,70,229,0.5)]"
            />
          </div>
          {/* Active Glow */}
          {progress < 100 && progress > 0 && (
            <div className="absolute inset-0 rounded-2xl bg-indigo-400 animate-ping opacity-20 scale-150" />
          )}
        </motion.div>
      </div>

      <motion.div
        initial={{ opacity: 0, x: side === 'left' ? -50 : 50, scale: 0.95 }}
        whileInView={{ opacity: 1, x: 0, scale: 1 }}
        viewport={{ once: true }}
        transition={{ duration: 0.6, delay }}
        className="w-full md:w-[calc(50%-2rem)] pl-16 md:pl-0"
      >
        <motion.div
          whileHover={{ y: -8, scale: 1.02 }}
          className="group relative bg-white p-8 rounded-[2.5rem] shadow-xl shadow-slate-200/50 border border-slate-100 hover:border-indigo-200 transition-all duration-300 overflow-hidden"
        >
          {/* Header Gradient */}
          <div className="absolute top-0 left-0 right-0 h-1.5 bg-gradient-to-r from-transparent via-indigo-400/30 to-transparent opacity-0 group-hover:opacity-100 transition-opacity" />

          <div className="flex flex-col gap-1 mb-6">
            <div className="flex items-center justify-between">
              <span className="text-[10px] font-black text-indigo-500 tracking-[0.2em]">{phase}</span>
              <div className="flex items-center gap-2">
                <div className="h-1.5 w-24 bg-slate-100 rounded-full overflow-hidden hidden sm:block">
                  <motion.div
                    initial={{ width: 0 }}
                    whileInView={{ width: `${progress}%` }}
                    className="h-full bg-indigo-500"
                  />
                </div>
                <span className="text-[10px] font-bold text-slate-400">{progress}%</span>
              </div>
            </div>
            <div className="flex items-center gap-3">
              <h3 className="font-black text-2xl text-slate-900 group-hover:text-indigo-600 transition-colors uppercase italic">{title}</h3>
              <div className="px-2 py-0.5 bg-slate-50 rounded-lg border border-slate-100 group-hover:bg-indigo-50 group-hover:border-indigo-100 transition-colors">
                <span className="text-[10px] font-bold text-slate-500 group-hover:text-indigo-500 uppercase">{label}</span>
              </div>
            </div>
          </div>

          <div className="space-y-6">
            <div className="relative">
              <div className="flex items-center justify-between mb-3">
                <span className="text-[10px] uppercase font-black text-slate-400 tracking-widest flex items-center gap-2">
                  <div className="w-1 h-1 bg-indigo-400 rounded-full" />
                  Primary Objectives
                </span>
                <button
                  onClick={() => setIsExpanded(!isExpanded)}
                  className="p-1 hover:bg-slate-100 rounded-lg transition-colors md:hidden"
                >
                  {isExpanded ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
                </button>
              </div>

              <AnimatePresence>
                {isExpanded && (
                  <motion.ul
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: 'auto', opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    className="space-y-2.5 overflow-hidden"
                  >
                    {data.goals.map((goal: string, idx: number) => (
                      <li key={idx} className="text-sm text-slate-600 font-semibold flex gap-3 group/li">
                        <div className="mt-1.5 p-0.5 bg-indigo-50 rounded-md group-hover/li:bg-indigo-100 transition-colors">
                          <Check size={10} className="text-indigo-600" />
                        </div>
                        {goal}
                      </li>
                    ))}
                  </motion.ul>
                )}
              </AnimatePresence>
            </div>

            <div>
              <span className="text-[10px] uppercase font-black text-slate-400 tracking-widest flex items-center gap-2 mb-3">
                <div className="w-1 h-1 bg-emerald-400 rounded-full" />
                Key Deliverables
              </span>
              <div className="flex flex-wrap gap-2">
                {data.features.map((feat: string, idx: number) => (
                  <motion.span
                    whileHover={{ scale: 1.05 }}
                    key={idx}
                    className="px-3 py-1 bg-emerald-50 text-emerald-700 rounded-xl text-[10px] font-black border border-emerald-100 hover:bg-emerald-100 transition-colors cursor-default"
                  >
                    {feat}
                  </motion.span>
                ))}
              </div>
            </div>
          </div>

          {/* Progress Bar Footer */}
          <div className="absolute bottom-0 left-0 right-0 h-1 bg-slate-50">
            <motion.div
              initial={{ width: 0 }}
              whileInView={{ width: `${progress}%` }}
              transition={{ duration: 1, delay: delay + 0.5 }}
              className="h-full bg-indigo-500 opacity-20"
            />
          </div>
        </motion.div>
      </motion.div>
      <div className="hidden md:block w-[calc(50%-2rem)]" />
    </div>
  );
};

const TechGroup = ({ title, icon, items, color }: { title: string, icon: React.ReactNode, items: string[], color: string }) => {
  if (items.length === 0) return null;

  const colorMap: Record<string, string> = {
    indigo: "bg-indigo-50 text-indigo-700 border-indigo-100",
    violet: "bg-violet-50 text-violet-700 border-violet-100",
    blue: "bg-blue-50 text-blue-700 border-blue-100",
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-2 text-slate-400">
        {icon}
        <span className="text-[10px] font-black uppercase tracking-widest">{title}</span>
      </div>
      <div className="flex flex-wrap gap-2">
        {items.map((item, idx) => (
          <motion.span
            whileHover={{ y: -2 }}
            key={idx}
            className={cn("px-3 py-1 rounded-xl text-xs font-bold border transition-all", colorMap[color])}
          >
            {item}
          </motion.span>
        ))}
      </div>
    </div>
  );
};
